lang: zh-CN
timezone: Asia/Shanghai

title: 系统工程/科学
tagline: 站在巨人的肩膀上，追求卓越，探索发现
description: >-
  站在巨人的肩膀上，追求卓越，探索发现
url: "https://xuleixie.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

github:
  username: xuleixie

twitter:
  username: xiexulei3

social:
  name: xulei Xie
  email: xuleixie@gmail.com
  links:
    - https://github.com/xuleixie
    - https://x.com/xiexulei3

theme_mode: dark

avatar: ""

toc: true

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json
  - node_modules
